// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.Infra.Context;

namespace Services.Infra.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20200401033432_payment5")]
    partial class payment5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Services.Domain.Entities.AirPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("AirPlane");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b413cfc0-f53a-4765-9430-3912efcd79cb"),
                            Code = "1",
                            CreationDate = new DateTime(2020, 4, 1, 0, 34, 30, 769, DateTimeKind.Local).AddTicks(9409),
                            ModelId = new Guid("7f430a38-a6b2-4a8f-96d5-801725dfdfc1"),
                            NumberOfPassengers = 111
                        },
                        new
                        {
                            Id = new Guid("a714554f-f363-42f1-b41a-81ee85186622"),
                            Code = "3B",
                            CreationDate = new DateTime(2020, 4, 1, 0, 34, 30, 778, DateTimeKind.Local).AddTicks(5576),
                            ModelId = new Guid("7f430a38-a6b2-4a8f-96d5-801725dfdfc3"),
                            NumberOfPassengers = 167
                        },
                        new
                        {
                            Id = new Guid("a714554f-f363-42f1-b41a-81ee85186661"),
                            Code = "4",
                            CreationDate = new DateTime(2020, 4, 1, 0, 34, 30, 778, DateTimeKind.Local).AddTicks(5875),
                            ModelId = new Guid("7f430a38-a6b2-4a8f-96d5-801725dfdfc4"),
                            NumberOfPassengers = 117
                        });
                });

            modelBuilder.Entity("Services.Domain.Entities.AirPlaneModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AirPlaneModel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f430a38-a6b2-4a8f-96d5-801725dfdfc1"),
                            Name = "Airbus A300B1"
                        },
                        new
                        {
                            Id = new Guid("7f430a38-a6b2-4a8f-96d5-801725dfdfc2"),
                            Name = "Airbus A319"
                        },
                        new
                        {
                            Id = new Guid("7f430a38-a6b2-4a8f-96d5-801725dfdfc3"),
                            Name = "Boeing 737-100"
                        },
                        new
                        {
                            Id = new Guid("7f430a38-a6b2-4a8f-96d5-801725dfdfc4"),
                            Name = "Boeing CRJ-100"
                        });
                });

            modelBuilder.Entity("Services.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaidDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b413cfc0-f53a-4765-9430-3912efcd79cb"),
                            BarCode = "0000 1111 2222 3333 4444",
                            Description = "Rent",
                            DueDate = "05/04/2020",
                            PaidDate = "05/04/2020"
                        });
                });

            modelBuilder.Entity("Services.Domain.Entities.AirPlane", b =>
                {
                    b.HasOne("Services.Domain.Entities.AirPlaneModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
